name: tennis at home
favicon: null
layout_spectrum: 0.26645
typography_spectrum: 0.23461
title: TennIS@homeSYD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a3c'
    - '#1690cf'
    - '#fcb316'
    - '#f16226'
  brandStrength: 0.40527090849354863
  lightness: 0.5359063479118049
  saturation: 0.6855313014239073
  rhythmicContrast: 0.5898196902126074
purpose: []
